/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Doctor;

import Business.BloodRequestQueue.BloodWorkRequest;
import Business.EcoSystem;
import Business.Enterprise.BloodBank;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khushbu
 */
public class AskForBloodJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Patient patient;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;
    private UserAccount account;

    /**
     * Creates new form AskForBloodJPanel
     */
    public AskForBloodJPanel(JPanel userProcessContainer, UserAccount account, Patient patient, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.enterprise = enterprise;
        this.system = system;
        this.network = network;
        this.account = account;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) bloodRequestsjTable.getModel();

        model.setRowCount(0);

        for (BloodWorkRequest request : account.getBloodWorkQueue().getWorkRequestList()) {
            if(request.getPatient()==patient){
            Object row[] = new Object[8];
            row[0] = request.getPatient().getName();
            row[1] = request.getPatient().getType();
             UserAccount result = request.getSender();
            row[2] = result == null ? "Sensor" : result;
            row[3] = request.getReceiver();
            row[4] = request.getStatus();
            row[5] = request.getRequestDate();
            row[6] = request.getResolveDate();
            row[7] = request.getQuantity();

            ((DefaultTableModel) bloodRequestsjTable.getModel()).addRow(row);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bloodRequestsjTable = new javax.swing.JTable();
        requestjButton = new javax.swing.JButton();
        quantityjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        bloodRequestsjTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bloodRequestsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient", "Blood Type", "Sender", "Receiver", "Status", "RequestDate", "ResolveDate", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bloodRequestsjTable);

        requestjButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        requestjButton.setText("Request");
        requestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestjButtonActionPerformed(evt);
            }
        });

        quantityjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        quantityjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityjTextFieldKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(quantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(requestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestjButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestjButtonActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        Enterprise inEnterprise = null;
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof BloodBank) {

                inEnterprise = e;
                break;

            }
        }
        if (quantityjTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide input for all fields", "Incomplete Form", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int quant = Integer.parseInt(quantityjTextField.getText());

        BloodWorkRequest br = new BloodWorkRequest();
        br.setQuantity(quant);
        br.setPatient(patient);
        br.setSender(account);
        br.setType(patient.getType());
        br.setRequestDate(date);
        br.setStatus("Request Sent");
        account.getBloodWorkQueue().getWorkRequestList().add(br);
        inEnterprise.getBloodWorkQueue().getWorkRequestList().add(br);


    }//GEN-LAST:event_requestjButtonActionPerformed

    private void quantityjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityjTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityjTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bloodRequestsjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantityjTextField;
    private javax.swing.JButton requestjButton;
    // End of variables declaration//GEN-END:variables
}
