/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Pharmacy;

import Business.Drugs.Drug;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khushbu
 */
public class ManageDrugInventoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;

    /**
     * Creates new form ManageDrugInventoryJPanel
     */
    public ManageDrugInventoryJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        contentsjLabel.setVisible(false);
        costjLabel.setVisible(false);
        namejLabel.setVisible(false);
        popData();
    }

    public void popData() {
        DefaultTableModel model = (DefaultTableModel) drugCatalogjTable.getModel();

        model.setRowCount(0);

        for (Drug drug : enterprise.getDrugDirectory().getDrugList()) {
            Object row[] = new Object[5];
            row[0] = drug;
            row[1] = drug.getDrugContents();
            row[2] = drug.getDrugexpiryDate();
            row[3] = drug.getAvailableQuantity();
            row[4] = drug.getDrugCost();

            ((DefaultTableModel) drugCatalogjTable.getModel()).addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addDrugjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugCatalogjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        drugNamejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        drugContentsjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        drugCostjTextField = new javax.swing.JTextField();
        datejDateChooser = new com.toedter.calendar.JDateChooser();
        namejLabel = new javax.swing.JLabel();
        contentsjLabel = new javax.swing.JLabel();
        costjLabel = new javax.swing.JLabel();
        availableQuantityjTextField = new javax.swing.JSpinner();

        addDrugjButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addDrugjButton.setText("Add Drug");
        addDrugjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugjButtonActionPerformed(evt);
            }
        });

        drugCatalogjTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        drugCatalogjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Drug Contents ", "Expiry Date", "Quantity", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(drugCatalogjTable);
        if (drugCatalogjTable.getColumnModel().getColumnCount() > 0) {
            drugCatalogjTable.getColumnModel().getColumn(0).setResizable(false);
            drugCatalogjTable.getColumnModel().getColumn(1).setResizable(false);
            drugCatalogjTable.getColumnModel().getColumn(2).setResizable(false);
            drugCatalogjTable.getColumnModel().getColumn(3).setResizable(false);
            drugCatalogjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Manage Drug Catalog");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Drug Name");

        drugNamejTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        drugNamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                drugNamejTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Drug Contents");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("DrugExpiryDate");

        drugContentsjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugContentsjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                drugContentsjTextFieldKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Available Quantity");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Drug Cost");

        drugCostjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        drugCostjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                drugCostjTextFieldKeyTyped(evt);
            }
        });

        datejDateChooser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        namejLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        namejLabel.setForeground(new java.awt.Color(255, 51, 51));
        namejLabel.setText("*Alphanumeric Only");

        contentsjLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contentsjLabel.setForeground(new java.awt.Color(255, 51, 51));
        contentsjLabel.setText("*Alphanumeric Only");

        costjLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        costjLabel.setForeground(new java.awt.Color(255, 51, 51));
        costjLabel.setText("*Numeric Only");

        availableQuantityjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        availableQuantityjTextField.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(439, 439, 439))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7))
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(drugNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(availableQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(namejLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(42, 42, 42)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(drugCostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(costjLabel))
                                    .addComponent(datejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addDrugjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(drugContentsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(contentsjLabel)))
                        .addGap(88, 88, 88))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6)
                        .addComponent(drugNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(namejLabel))
                    .addComponent(datejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(drugCostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costjLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(drugContentsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(contentsjLabel)
                        .addComponent(addDrugjButton)))
                .addContainerGap(539, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDrugjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugjButtonActionPerformed
         Date date =datejDateChooser.getDate() ;
        Date sysdate = new Date();
        
        if (drugNamejTextField.getText().trim().isEmpty() || drugContentsjTextField.getText().trim().isEmpty()
                || drugCostjTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory!", "Warning", JOptionPane.INFORMATION_MESSAGE);

        } else if(date==null)
        {
        JOptionPane.showMessageDialog(null, "Please select a Date!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(sysdate.after(date))
        {
        JOptionPane.showMessageDialog(null, "Expiry Dte should be greater than today's date!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if ((Integer) availableQuantityjTextField.getValue() <= 0) {
                JOptionPane.showMessageDialog(null, "Available Quantity Should be greater than 0!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else{
            Drug drug = enterprise.getDrugDirectory().addDrug();
            drug.setDrugName(drugNamejTextField.getText());
            drug.setDrugContents(drugContentsjTextField.getText());
            drug.setDrugCost(Integer.parseInt(drugCostjTextField.getText()));

            drug.setAvailableQuantity((Integer) availableQuantityjTextField.getValue());

            drug.setDrugexpiryDate(datejDateChooser.getDate());
            JOptionPane.showMessageDialog(null, "Drug Added Successfully!", "Drug entry Created", JOptionPane.INFORMATION_MESSAGE);
            popData();
            }
    }//GEN-LAST:event_addDrugjButtonActionPerformed

    private void drugContentsjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drugContentsjTextFieldKeyTyped
        char a = evt.getKeyChar();
        if (!(Character.isDigit(a) || Character.isAlphabetic(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            contentsjLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_drugContentsjTextFieldKeyTyped

    private void drugCostjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drugCostjTextFieldKeyTyped
        char a = evt.getKeyChar();
        if (!(Character.isDigit(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            costjLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_drugCostjTextFieldKeyTyped

    private void drugNamejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drugNamejTextFieldKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (!(Character.isDigit(a) || Character.isAlphabetic(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            namejLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_drugNamejTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrugjButton;
    private javax.swing.JSpinner availableQuantityjTextField;
    private javax.swing.JLabel contentsjLabel;
    private javax.swing.JLabel costjLabel;
    private com.toedter.calendar.JDateChooser datejDateChooser;
    private javax.swing.JTable drugCatalogjTable;
    private javax.swing.JTextField drugContentsjTextField;
    private javax.swing.JTextField drugCostjTextField;
    private javax.swing.JTextField drugNamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namejLabel;
    // End of variables declaration//GEN-END:variables
}
