/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.BloodBankStores.Blood;
import Business.Db4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NewOrganization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author khushbu
 */
public class MyProfileJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;
    private Enterprise enterprise;
    private NewOrganization organization;
    private Network network;

    /**
     * Creates new form MyProfileJPanel
     */
    public MyProfileJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, NewOrganization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        PopulateDetails();
        resetFields();
    }

    public void populateCombobox()
    {
   bloodgroupjComboBox.removeAllItems();
        for (Blood.BloodType type : Blood.BloodType.values()) {
            bloodgroupjComboBox.addItem(type);
        }
    }
    public void resetFields() {
        namejLabel.setVisible(false);
        addressjLabel.setVisible(false);
        phnojLabel.setVisible(false);
        emailAddressjLabel.setVisible(false);
        dobjLabel.setVisible(false);
        bloodgroupjLabel.setVisible(false);

    }
     public boolean validateEmailId(String emailId) {
        String email = emailId;
        boolean isValid = false;
        String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
        CharSequence inputStr = email;
//Make the comparison case-insensitive.  
        Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(inputStr);
        if (matcher.matches()) {
            isValid = true;
        }
        return isValid;
        
    }

    public void PopulateDetails() {
        patientNamejTextField.setText(account.getPatient().getName());
        addressjTextArea.setText(account.getPatient().getAddress());
        emailAddressjTextField.setText(account.getPatient().getEmailID());
        datejDateChooser.setDate(account.getPatient().getDateOfBirth());
        bloodgroupjComboBox.removeAllItems();
        bloodgroupjComboBox.addItem(account.getPatient().getType());
        phoneNumberjTextField.setText(String.valueOf(account.getPatient().getPhoneNumber()));
//        genderjTextField.setText(String.valueOf(account.getPatient().getPhoneNumber()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        datejDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        emailAddressjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientNamejTextField = new javax.swing.JTextField();
        phoneNumberjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressjTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        editjButton = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();
        namejLabel = new javax.swing.JLabel();
        dobjLabel = new javax.swing.JLabel();
        addressjLabel = new javax.swing.JLabel();
        emailAddressjLabel = new javax.swing.JLabel();
        phnojLabel = new javax.swing.JLabel();
        bloodgroupjLabel = new javax.swing.JLabel();
        bloodgroupjComboBox = new javax.swing.JComboBox();

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Blood Group");

        datejDateChooser.setEnabled(false);
        datejDateChooser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Email address");

        emailAddressjTextField.setEditable(false);
        emailAddressjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailAddressjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailAddressjTextFieldKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Patient Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Phone Number");

        patientNamejTextField.setEditable(false);
        patientNamejTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        patientNamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patientNamejTextFieldKeyTyped(evt);
            }
        });

        phoneNumberjTextField.setEditable(false);
        phoneNumberjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoneNumberjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberjTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Address");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Date Of Birth");

        addressjTextArea.setEditable(false);
        addressjTextArea.setColumns(20);
        addressjTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        addressjTextArea.setRows(5);
        addressjTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressjTextAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(addressjTextArea);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("My Profile");

        editjButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        editjButton.setText("Edit");
        editjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButtonActionPerformed(evt);
            }
        });

        savejButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        savejButton.setText("Save");
        savejButton.setEnabled(false);
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        namejLabel.setForeground(new java.awt.Color(255, 0, 51));
        namejLabel.setText("*Albhabets Only");

        dobjLabel.setForeground(new java.awt.Color(255, 0, 51));
        dobjLabel.setText("*select a date");

        addressjLabel.setForeground(new java.awt.Color(255, 0, 51));
        addressjLabel.setText("*AlphaNumeric Only");

        emailAddressjLabel.setForeground(new java.awt.Color(255, 0, 51));
        emailAddressjLabel.setText("*Invalid Format");

        phnojLabel.setForeground(new java.awt.Color(255, 0, 51));
        phnojLabel.setText("*Numeric Only");

        bloodgroupjLabel.setForeground(new java.awt.Color(255, 0, 51));
        bloodgroupjLabel.setText("*");

        bloodgroupjComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bloodgroupjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bloodgroupjComboBox.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailAddressjLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4))
                            .addComponent(addressjLabel)
                            .addComponent(emailAddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(editjButton)
                                .addGap(69, 69, 69)
                                .addComponent(savejButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bloodgroupjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bloodgroupjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namejLabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phnojLabel)
                                    .addComponent(dobjLabel))))
                        .addGap(129, 129, 129))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(53, 53, 53)
                    .addComponent(patientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(datejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(namejLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(dobjLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(phnojLabel)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)))))
                .addComponent(addressjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(emailAddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailAddressjLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bloodgroupjLabel)
                    .addComponent(bloodgroupjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editjButton)
                    .addComponent(savejButton))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(patientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addComponent(datejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButtonActionPerformed
        // TODO add your handling code here:

        savejButton.setEnabled(true);
        patientNamejTextField.setEditable(true);
        addressjTextArea.setEditable(true);
        emailAddressjTextField.setEditable(true);
        datejDateChooser.setEnabled(true);
//        bloodGroupjTextField.setEditable(true);
        phoneNumberjTextField.setEditable(true);
//        genderjTextField.setEditable(true);

        editjButton.setEnabled(false);

    }//GEN-LAST:event_editjButtonActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        if (patientNamejTextField.getText().trim().isEmpty() || addressjTextArea.getText().trim().isEmpty() || emailAddressjTextField.getText().trim().isEmpty()|| phoneNumberjTextField.getText().trim().isEmpty() || datejDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please provide input for all fields", "Incomplete Form", JOptionPane.INFORMATION_MESSAGE);
        } else {

            String emailId = emailAddressjTextField.getText();
            Date dateOfBirth = datejDateChooser.getDate();

            Date today = new Date();
            boolean check = validateEmailId(emailId);
            if (!check) {
                emailAddressjLabel.setVisible(true);
            } else if (dateOfBirth.after(today)) {
                JOptionPane.showMessageDialog(null, "Date of birth date shoul not be greater than todays date!!", "Incomplete Form", JOptionPane.INFORMATION_MESSAGE);
            } else {
                account.getPatient().setName(patientNamejTextField.getText());
                account.getPatient().setAddress(addressjTextArea.getText());
                account.getPatient().setEmailID(emailAddressjTextField.getText());
                account.getPatient().setDateOfBirth(datejDateChooser.getDate());
//                account.getPatient().setBloodGroup(bloodGroupjTextField.getText());
                account.getPatient().setPhoneNumber(Integer.parseInt(phoneNumberjTextField.getText()));
//                account.getPatient().setGender(genderjTextField.getText());
                JOptionPane.showMessageDialog(null, "Patient detail updated!!", "Successful", JOptionPane.INFORMATION_MESSAGE);
                resetFields();
                editjButton.setEnabled(true);
                savejButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void patientNamejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientNamejTextFieldKeyTyped
        // TODO add your handling code here:
             char a = evt.getKeyChar();
        if (!(Character.isAlphabetic(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            namejLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_patientNamejTextFieldKeyTyped

    private void addressjTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressjTextAreaKeyTyped
        // TODO add your handling code here:
             char a = evt.getKeyChar();
        if (!(Character.isDigit(a) ||Character.isAlphabetic(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            addressjLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_addressjTextAreaKeyTyped

    private void emailAddressjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailAddressjTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressjTextFieldKeyTyped

    private void phoneNumberjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberjTextFieldKeyTyped
        // TODO add your handling code here:
               char a = evt.getKeyChar();
        if (!(Character.isDigit(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            phnojLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberjTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JTextArea addressjTextArea;
    private javax.swing.JComboBox bloodgroupjComboBox;
    private javax.swing.JLabel bloodgroupjLabel;
    private com.toedter.calendar.JDateChooser datejDateChooser;
    private javax.swing.JLabel dobjLabel;
    private javax.swing.JButton editjButton;
    private javax.swing.JLabel emailAddressjLabel;
    private javax.swing.JTextField emailAddressjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField patientNamejTextField;
    private javax.swing.JLabel phnojLabel;
    private javax.swing.JTextField phoneNumberjTextField;
    private javax.swing.JButton savejButton;
    // End of variables declaration//GEN-END:variables
}
