/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LaboratoryEnterprise;
import Business.ExportToExcel.ExcelExport;
import Business.LabTestWorkRequest.LabTestWorkRequest;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.Organization.NewOrganization;
import Business.UserAccount.UserAccount;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khushbu
 */
public class MyReportsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private Enterprise enterprise;
    private NewOrganization organization;
    private Network network;

    /**
     * Creates new form MyReportsJPanel
     */
    public MyReportsJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, NewOrganization organization, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        populateTable();
    }

    public void populateTable() {
        NewOrganization org = null;
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof LaboratoryEnterprise) {
                for (NewOrganization organization : e.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof LabOrganization) {
                        org = organization;
                        break;
                    }
                }
            }
        }
        for (LabTestWorkRequest request : org.getLabTestWorkQueue().getWorkRequestList()) {
            if(request==null){break;}
            if (request.getPatient().equals(account.getPatient())) {
                Object row[] = new Object[9];
                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getReceiver();
                row[3] = request.getPatient();
                row[4] = request.getStatus();
                row[5] = request.getResult();
                row[6] = request.getResultDesc();
                row[7] = request.getRequestDate();
                row[8] = request.getDeliveredDate();

                ((DefaultTableModel) labTestworkRequestjTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        labTestworkRequestjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        exportToExceljButton = new javax.swing.JButton();

        labTestworkRequestjTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labTestworkRequestjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Name", "Sender", "Receiver", "Status", "Result", "Request Sent Date", "Completed Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(labTestworkRequestjTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("My Reports");

        exportToExceljButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exportToExceljButton.setText("Export to Excel");
        exportToExceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportToExceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exportToExceljButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(exportToExceljButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exportToExceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportToExceljButtonActionPerformed
        // TODO add your handling code here:
        String[][] data = {};

        String[] headers = {"BodyTemperature", "BloodPressure", "HeartRate", "RespiratoryRate", "Weight", "BloodSugarLevel", "UpdatedDttm", "Checkedby"};

        JFrame frame = new JFrame("Excel");
        DefaultTableModel newmodel = new DefaultTableModel(data, headers);
        final JTable table = new JTable(newmodel);
        JScrollPane scroll = new JScrollPane(table);
        JButton export = new JButton("Export");
        export.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
  ExcelExport excel = new ExcelExport();
  
                    excel.exportTable(labTestworkRequestjTable, new File("Report"+account.getPatient().getName()+".xls"));
                } catch (IOException e) {
                    e.getMessage();
                }
            }
        });

        frame.getContentPane().add(scroll);
        frame.getContentPane().add(export);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_exportToExceljButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportToExceljButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable labTestworkRequestjTable;
    // End of variables declaration//GEN-END:variables
}
