/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Db4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NewOrganization;
import Business.Sensors.Sensor;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author khushbu
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;
    private Enterprise enterprise;
    private NewOrganization organization; 
    private Network network;
    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,EcoSystem system,Enterprise enterprise,Network network,NewOrganization organization,DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.enterprise = enterprise;
        this.organization=organization;
        this.network=network;
        welcomejLabel.setText("Welcome " + account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoutjButton = new javax.swing.JButton();
        welcomejLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        myMedicnejButton = new javax.swing.JButton();
        myReportsjButton = new javax.swing.JButton();
        myVitalSignsjButton = new javax.swing.JButton();
        myAppointmentsjButton = new javax.swing.JButton();
        myProfilejButton = new javax.swing.JButton();
        callTheAmbulancejButton = new javax.swing.JButton();
        myInsuracejButton = new javax.swing.JButton();
        receptionistContainer = new javax.swing.JPanel();

        logoutjButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logoutjButton.setText("Logout");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        welcomejLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        welcomejLabel.setForeground(new java.awt.Color(0, 0, 255));
        welcomejLabel.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/health-care.jpg"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        myMedicnejButton.setText("My Medicine");
        myMedicnejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myMedicnejButtonActionPerformed(evt);
            }
        });

        myReportsjButton.setText("My Reports");
        myReportsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myReportsjButtonActionPerformed(evt);
            }
        });

        myVitalSignsjButton.setText("My vitalSigns");
        myVitalSignsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myVitalSignsjButtonActionPerformed(evt);
            }
        });

        myAppointmentsjButton.setText("My Appointments");
        myAppointmentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAppointmentsjButtonActionPerformed(evt);
            }
        });

        myProfilejButton.setText("My Profile");
        myProfilejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfilejButtonActionPerformed(evt);
            }
        });

        callTheAmbulancejButton.setText("Call The Ambulance");
        callTheAmbulancejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callTheAmbulancejButtonActionPerformed(evt);
            }
        });

        myInsuracejButton.setText("My Insurace");
        myInsuracejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myInsuracejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myReportsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myMedicnejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myVitalSignsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myAppointmentsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myProfilejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(callTheAmbulancejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(myInsuracejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(myProfilejButton)
                .addGap(18, 18, 18)
                .addComponent(myInsuracejButton)
                .addGap(18, 18, 18)
                .addComponent(myAppointmentsjButton)
                .addGap(18, 18, 18)
                .addComponent(myVitalSignsjButton)
                .addGap(18, 18, 18)
                .addComponent(myMedicnejButton)
                .addGap(18, 18, 18)
                .addComponent(myReportsjButton)
                .addGap(13, 13, 13)
                .addComponent(callTheAmbulancejButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        receptionistContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(receptionistContainer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomejLabel)
                .addGap(88, 88, 88)
                .addComponent(logoutjButton)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutjButton)
                    .addComponent(welcomejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 421, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 320, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void myMedicnejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myMedicnejButtonActionPerformed
               
                MyMedicineJPanel myMedicineJPanel = new MyMedicineJPanel(receptionistContainer, account, enterprise,network,organization, system);
                receptionistContainer.add("MyMedicineJPanel", myMedicineJPanel);
                CardLayout layout = (CardLayout) receptionistContainer.getLayout();
                layout.next(receptionistContainer);
    }//GEN-LAST:event_myMedicnejButtonActionPerformed

    private void myReportsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myReportsjButtonActionPerformed
        // TODO add your handling code here:
                MyReportsJPanel myReportsJPanel = new MyReportsJPanel(receptionistContainer, account, enterprise,network,organization, system);
                receptionistContainer.add("MyReportsJPanel", myReportsJPanel);
                CardLayout layout = (CardLayout) receptionistContainer.getLayout();
                layout.next(receptionistContainer);
    }//GEN-LAST:event_myReportsjButtonActionPerformed

    private void myVitalSignsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myVitalSignsjButtonActionPerformed
        // TODO add your handling code here:
        MyVitalSignsJPanel myVitalSignsJPanel = new MyVitalSignsJPanel(receptionistContainer, account, enterprise,network,organization, system);
        receptionistContainer.add("MyVitalSignsJPanel", myVitalSignsJPanel);
        CardLayout layout = (CardLayout) receptionistContainer.getLayout();
        layout.next(receptionistContainer);
    }//GEN-LAST:event_myVitalSignsjButtonActionPerformed

    private void myAppointmentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAppointmentsjButtonActionPerformed
        // TODO add your handling code here:
        MyAppointmentsJPanel myAppointmentsJPanel = new MyAppointmentsJPanel(receptionistContainer, account, enterprise,network,organization, system);
        receptionistContainer.add("MyAppointmentsJPanel", myAppointmentsJPanel);
        CardLayout layout = (CardLayout) receptionistContainer.getLayout();
        layout.next(receptionistContainer);
    }//GEN-LAST:event_myAppointmentsjButtonActionPerformed

    private void myProfilejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfilejButtonActionPerformed
        // TODO add your handling code here:
        MyProfileJPanel myProfileJPanel = new MyProfileJPanel(receptionistContainer, account, enterprise,network,organization, system);
        receptionistContainer.add("MyProfileJPanel", myProfileJPanel);
        CardLayout layout = (CardLayout) receptionistContainer.getLayout();
        layout.next(receptionistContainer);
    }//GEN-LAST:event_myProfilejButtonActionPerformed

    private void callTheAmbulancejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callTheAmbulancejButtonActionPerformed
        // TODO add your handling code here:
        CallTheAmbulanceJPanel callTheAmbulanceJPanel = new CallTheAmbulanceJPanel(receptionistContainer, account, enterprise,network,organization, system);
        receptionistContainer.add("CallTheAmbulanceJPanel", callTheAmbulanceJPanel);
        CardLayout layout = (CardLayout) receptionistContainer.getLayout();
        layout.next(receptionistContainer);
    }//GEN-LAST:event_callTheAmbulancejButtonActionPerformed

    private void myInsuracejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myInsuracejButtonActionPerformed
        // TODO add your handling code here:
        MyInsuranceJPanel myInsuranceJPanel = new MyInsuranceJPanel(receptionistContainer, account, enterprise,network,organization, system);
        receptionistContainer.add("MyInsuranceJPanel", myInsuranceJPanel);
        CardLayout layout = (CardLayout) receptionistContainer.getLayout();
        layout.next(receptionistContainer);
    }//GEN-LAST:event_myInsuracejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton callTheAmbulancejButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JButton myAppointmentsjButton;
    private javax.swing.JButton myInsuracejButton;
    private javax.swing.JButton myMedicnejButton;
    private javax.swing.JButton myProfilejButton;
    private javax.swing.JButton myReportsjButton;
    private javax.swing.JButton myVitalSignsjButton;
    private javax.swing.JPanel receptionistContainer;
    private javax.swing.JLabel welcomejLabel;
    // End of variables declaration//GEN-END:variables
}
