/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Db4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import UserInterface.SysadminReports.ReportsNewJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author khushbu
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        welcomejLabel.setText("Welcome " + account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutjButton = new javax.swing.JButton();
        welcomejLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        manageNetworkjButton = new javax.swing.JButton();
        manageEnterprisejButton = new javax.swing.JButton();
        manageEnterpriseAccessjButton = new javax.swing.JButton();
        reportsjButton = new javax.swing.JButton();
        sysAdminContainer = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutjButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logoutjButton.setText("Logout");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });
        add(logoutjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, -1, -1));

        welcomejLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        welcomejLabel.setForeground(new java.awt.Color(0, 0, 255));
        welcomejLabel.setText("jLabel1");
        add(welcomejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/health-care.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 51, -1, 263));

        jPanel1.setLayout(new java.awt.CardLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 622, -1, -1));

        jLayeredPane1.setLayout(new java.awt.BorderLayout());
        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 615, -1, -1));

        jPanel2.setLayout(new java.awt.CardLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 499, -1, -1));

        jLayeredPane2.setLayout(new java.awt.CardLayout());
        add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 558, -1, -1));

        jLayeredPane3.setLayout(new java.awt.BorderLayout());
        add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 608, -1, -1));

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jLayeredPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 400, -1));

        manageNetworkjButton.setText("Manage Network");
        manageNetworkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkjButtonActionPerformed(evt);
            }
        });

        manageEnterprisejButton.setText("Manage Enterprise");
        manageEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterprisejButtonActionPerformed(evt);
            }
        });

        manageEnterpriseAccessjButton.setText("Manage Enterprise Acess");
        manageEnterpriseAccessjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAccessjButtonActionPerformed(evt);
            }
        });

        reportsjButton.setText("Reports");
        reportsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageEnterpriseAccessjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageEnterprisejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageNetworkjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportsjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(manageNetworkjButton)
                .addGap(40, 40, 40)
                .addComponent(manageEnterprisejButton)
                .addGap(36, 36, 36)
                .addComponent(manageEnterpriseAccessjButton)
                .addGap(35, 35, 35)
                .addComponent(reportsjButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        sysAdminContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(sysAdminContainer);

        add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 327, 1090, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void manageNetworkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkjButtonActionPerformed
        // TODO add your handling code here:
        ManageNetworksJPanel manageNetworksJPanel = new ManageNetworksJPanel(sysAdminContainer, system);
        sysAdminContainer.add("manageNetworkJPanel", manageNetworksJPanel);
        CardLayout layout = (CardLayout) sysAdminContainer.getLayout();
        layout.next(sysAdminContainer);
    }//GEN-LAST:event_manageNetworkjButtonActionPerformed

    private void manageEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterprisejButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(sysAdminContainer, system);
        sysAdminContainer.add("ManageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) sysAdminContainer.getLayout();
        layout.next(sysAdminContainer);
    }//GEN-LAST:event_manageEnterprisejButtonActionPerformed

    private void manageEnterpriseAccessjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAccessjButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAccessJPanel manageEnterpriseAccessJPanel = new ManageEnterpriseAccessJPanel(sysAdminContainer, system);
        sysAdminContainer.add("ManageEnterpriseAccessJPanel", manageEnterpriseAccessJPanel);
        CardLayout layout = (CardLayout) sysAdminContainer.getLayout();
        layout.next(sysAdminContainer);
    }//GEN-LAST:event_manageEnterpriseAccessjButtonActionPerformed

    private void reportsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsjButtonActionPerformed
        // TODO add your handling code here:
        ReportsNewJPanel reportsNewJPanel = new ReportsNewJPanel(sysAdminContainer, system);
        sysAdminContainer.add("ReportsNewJPanel", reportsNewJPanel);
        CardLayout layout = (CardLayout) sysAdminContainer.getLayout();
        layout.next(sysAdminContainer);
    }//GEN-LAST:event_reportsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JButton manageEnterpriseAccessjButton;
    private javax.swing.JButton manageEnterprisejButton;
    private javax.swing.JButton manageNetworkjButton;
    private javax.swing.JButton reportsjButton;
    private javax.swing.JPanel sysAdminContainer;
    private javax.swing.JLabel welcomejLabel;
    // End of variables declaration//GEN-END:variables
}
