/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Receptionist;

import Business.BloodBankStores.Blood;
import Business.BloodBankStores.Blood.BloodType;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.NewOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author khushbu
 */
public class AddPatientJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private Enterprise enterprise;
    private NewOrganization organization;

    /**
     * Creates new form AddPatientJPanel
     */
    public AddPatientJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, NewOrganization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        resetFields();
        populateCombobox();
    }
    public void populateCombobox()
    {
   bloodgroupjComboBox.removeAllItems();
        for (Blood.BloodType type : Blood.BloodType.values()) {
            bloodgroupjComboBox.addItem(type);
        }
    }
    
    public void resetFields() {
        namejLabel.setVisible(false);
        addressjLabel.setVisible(false);
        phnojLabel.setVisible(false);
        emailAddressjLabel.setVisible(false);
        dobjLabel.setVisible(false);
        bloodgroupjLabel.setVisible(false);
        patientNamejTextField.setText("");
        addressjTextArea.setText("");
        emailAddressjTextField.setText("");
        datejDateChooser.setDate(null);
//        bloodGroupjTextField.setText("");
        phoneNumberjTextField.setText("");
    }

    public boolean validateEmailId(String emailId) {
        String email = emailId;
        boolean isValid = false;
        String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
        CharSequence inputStr = email;
//Make the comparison case-insensitive.  
        Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(inputStr);
        if (matcher.matches()) {
            isValid = true;
        }
        return isValid;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        patientNamejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressjTextArea = new javax.swing.JTextArea();
        datejDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        addPatientjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        emailAddressjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phoneNumberjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        bloodgroupjLabel = new javax.swing.JLabel();
        emailAddressjLabel = new javax.swing.JLabel();
        dobjLabel = new javax.swing.JLabel();
        phnojLabel = new javax.swing.JLabel();
        femaleRB = new javax.swing.JRadioButton();
        maleRB = new javax.swing.JRadioButton();
        bloodgroupjComboBox = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Patient Name");

        patientNamejTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        patientNamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patientNamejTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Address");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Date Of Birth");

        addressjTextArea.setColumns(20);
        addressjTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        addressjTextArea.setRows(5);
        addressjTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressjTextAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(addressjTextArea);

        datejDateChooser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Add Patient");

        addPatientjButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addPatientjButton.setText("Add");
        addPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientjButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Email address");

        emailAddressjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailAddressjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailAddressjTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Phone Number");

        phoneNumberjTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoneNumberjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberjTextFieldKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Blood Group");

        addressjLabel.setForeground(new java.awt.Color(255, 0, 51));
        addressjLabel.setText("*AlphaNumeric Only");

        namejLabel.setForeground(new java.awt.Color(255, 0, 51));
        namejLabel.setText("*Albhabets Only");

        bloodgroupjLabel.setForeground(new java.awt.Color(255, 0, 51));
        bloodgroupjLabel.setText("*");

        emailAddressjLabel.setForeground(new java.awt.Color(255, 0, 51));
        emailAddressjLabel.setText("*Invalid Format");

        dobjLabel.setForeground(new java.awt.Color(255, 0, 51));
        dobjLabel.setText("*select a date");

        phnojLabel.setForeground(new java.awt.Color(255, 0, 51));
        phnojLabel.setText("*Numeric Only");

        buttonGroup1.add(femaleRB);
        femaleRB.setText("Female");

        buttonGroup1.add(maleRB);
        maleRB.setText("Male");

        bloodgroupjComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bloodgroupjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(addPatientjButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailAddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namejLabel)
                                            .addComponent(addressjLabel)
                                            .addComponent(patientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)))
                                    .addComponent(emailAddressjLabel)
                                    .addComponent(bloodgroupjLabel)
                                    .addComponent(bloodgroupjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maleRB)
                                    .addComponent(phoneNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobjLabel)
                                    .addComponent(phnojLabel)
                                    .addComponent(femaleRB)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel4)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addComponent(datejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNamejTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(dobjLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(namejLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phnojLabel)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(femaleRB))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailAddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailAddressjLabel)
                            .addComponent(maleRB))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(13, 13, 13)
                        .addComponent(bloodgroupjLabel)
                        .addGap(5, 5, 5)
                        .addComponent(addPatientjButton))
                    .addComponent(bloodgroupjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientjButtonActionPerformed
        // TODO add your handling code here:
        if (patientNamejTextField.getText().trim().isEmpty() || addressjTextArea.getText().trim().isEmpty() || emailAddressjTextField.getText().trim().isEmpty()|| phoneNumberjTextField.getText().trim().isEmpty() || datejDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please provide input for all fields", "Incomplete Form", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String name = patientNamejTextField.getText();
            String address = addressjTextArea.getText();
            String emailId = emailAddressjTextField.getText();
            Date dateOfBirth = datejDateChooser.getDate();
//            String bloodGroup = bloodGroupjTextField.getText();
            
            int phoneNumber = Integer.parseInt(phoneNumberjTextField.getText());
//       String gender=genderjTextField.getText();
String gender ="";
            if(femaleRB.isSelected()){
                 gender = "Female";
            }
            else{
                 gender = "Male";
            }
            Date today=new Date();
            boolean check = validateEmailId(emailId);
            if (!check) {
                emailAddressjLabel.setVisible(true);
            } else if(dateOfBirth.after(today))
            {
             JOptionPane.showMessageDialog(null, "Date of birth date should not be greater than todays date!!", "Incomplete Form", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                Blood.BloodType type= (Blood.BloodType) bloodgroupjComboBox.getSelectedItem();
                Patient p = enterprise.getPatientDirectory().AddPatient(name, emailId, phoneNumber, address, dateOfBirth,gender, type, 'N');
                JOptionPane.showMessageDialog(null, "Patient Added!!", "Successful", JOptionPane.INFORMATION_MESSAGE);
                PatientUserAccountJPanel patientUserAccountJPanel = new PatientUserAccountJPanel(userProcessContainer, enterprise, organization, p, system);
                userProcessContainer.add("PatientUserAccountJPanel", patientUserAccountJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_addPatientjButtonActionPerformed

    private void patientNamejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientNamejTextFieldKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        
        if (!(Character.isAlphabetic(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            namejLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_patientNamejTextFieldKeyTyped

    private void addressjTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressjTextAreaKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        
        if (!(Character.isDigit(a) ||Character.isAlphabetic(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            addressjLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_addressjTextAreaKeyTyped

    private void emailAddressjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailAddressjTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressjTextFieldKeyTyped

    private void phoneNumberjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberjTextFieldKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (!(Character.isDigit(a) || a == KeyEvent.VK_DELETE || a == KeyEvent.VK_BACK_SPACE)) {
            phnojLabel.setVisible(true);
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberjTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientjButton;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JTextArea addressjTextArea;
    private javax.swing.JComboBox bloodgroupjComboBox;
    private javax.swing.JLabel bloodgroupjLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser datejDateChooser;
    private javax.swing.JLabel dobjLabel;
    private javax.swing.JLabel emailAddressjLabel;
    private javax.swing.JTextField emailAddressjTextField;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField patientNamejTextField;
    private javax.swing.JLabel phnojLabel;
    private javax.swing.JTextField phoneNumberjTextField;
    // End of variables declaration//GEN-END:variables
}
